[profile.default]
solc_version = '0.8.13' # Version of solc that we use
remappings = [ # Libraries that we use from node_modules and are used by the smart contracts
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@summa-tx/=node_modules/@summa-tx/",
  "@nomad-xyz/=packages/",
  "forge-std/=lib/forge-std/src/",
]
optimizer = true # Enable or disable the solc optimizer
optimizer_runs = 999999 # The number of optimizer runs
verbosity = 3 # The verbosity of tests
bytecode_hash = "none" # For deterministic code
